In [1]:
import pandas as pd
import sqlite3
import logging
from ingestion import ingest_db

In [2]:
conn=sqlite3.connect('inventory.db')

In [3]:
#checking tables present inside database
tables=pd.read_sql_query("SELECT name FROM sqlite_master WHERE type='table'",conn)
tables

                   name
0       begin_inventory
1         end_inventory
2             purchases
3       purchase_prices
4                 sales
5        vendor_invoice
6   vendor_sales_sumary
7   vendor_sales_number
8  vendor_sales_summary

In [4]:
pd.read_sql("select count(*) from purchases",conn)

   count(*)
0   2372474

In [7]:
for table in tables['name']:
    print('-'*50,f'{table}','-'*50)
    print('Count of Records:',pd.read_sql(f"select count(*) as count from {table}",conn)['count'].values[0])
    display(pd.read_sql(f"select * from {table}",conn))

-------------------------------------------------- begin_inventory --------------------------------------------------
Count of Records: 206529

,InventoryId,Store,City,Brand,Description,Size,onHand,Price,startDate
0,1_HARDERSFIELD_58,1,HARDERSFIELD,58,Gekkeikan Black & Gold Sake,750mL,8,12.99,2024-01-01
1,1_HARDERSFIELD_60,1,HARDERSFIELD,60,Canadian Club 1858 VAP,750mL,7,10.99,2024-01-01
2,1_HARDERSFIELD_62,1,HARDERSFIELD,62,Herradura Silver Tequila,750mL,6,36.99,2024-01-01
3,1_HARDERSFIELD_63,1,HARDERSFIELD,63,Herradura Reposado Tequila,750mL,3,38.99,2024-01-01
4,1_HARDERSFIELD_72,1,HARDERSFIELD,72,No. 3 London Dry Gin,750mL,6,34.99,2024-01-01
...,...,...,...,...,...,...,...,...,...
206524,79_BALLYMENA_46985,79,BALLYMENA,46985,Rodney Strong Cab Svgn Alexa,750mL,13,22.99,2024-01-01
206525,79_BALLYMENA_47014,79,BALLYMENA,47014,Juan Gil Jumilla Rd,750mL,13,13.99,2024-01-01
206526,79_BALLYMENA_47090,79,BALLYMENA,47090,Napa Cellars Cab Svgn Napa,750mL,19,23.99,2024-01-01
206527,79_BALLYMENA_90011,79,BALLYMENA,90011,Ch Pichon Longville 12 Pauil,750mL,12,144.99,2024-01-01
206528,79_BALLYMENA_90089,79,BALLYMENA,90089,Ch Lynch Bages 12 Pauillac,750mL,24,119.99,2024-01-01

-------------------------------------------------- end_inventory --------------------------------------------------
Count of Records: 224489

,InventoryId,Store,City,Brand,Description,Size,onHand,Price,endDate
0,1_HARDERSFIELD_58,1,HARDERSFIELD,58,Gekkeikan Black & Gold Sake,750mL,11,12.99,2024-12-31
1,1_HARDERSFIELD_62,1,HARDERSFIELD,62,Herradura Silver Tequila,750mL,7,36.99,2024-12-31
2,1_HARDERSFIELD_63,1,HARDERSFIELD,63,Herradura Reposado Tequila,750mL,7,38.99,2024-12-31
3,1_HARDERSFIELD_72,1,HARDERSFIELD,72,No. 3 London Dry Gin,750mL,4,34.99,2024-12-31
4,1_HARDERSFIELD_75,1,HARDERSFIELD,75,Three Olives Tomato Vodka,750mL,7,14.99,2024-12-31
...,...,...,...,...,...,...,...,...,...
224484,81_PEMBROKE_90087,81,PEMBROKE,90087,Ch Mouton Rothschild 12 Paui,750mL,3,469.99,2024-12-31
224485,81_PEMBROKE_90088,81,PEMBROKE,90088,Ch Le Petite Mouton 12 Pauil,750mL,3,134.99,2024-12-31
224486,81_PEMBROKE_90089,81,PEMBROKE,90089,Ch Lynch Bages 12 Pauillac,750mL,3,119.99,2024-12-31
224487,81_PEMBROKE_90090,81,PEMBROKE,90090,Ch Lafite Rothschild 12,750mL,3,649.99,2024-12-31
224488,81_PEMBROKE_90604,81,PEMBROKE,90604,Ch Lynch Bages Pauilac,750mL,2,119.99,2024-12-31

-------------------------------------------------- purchases --------------------------------------------------
Count of Records: 2372474

,InventoryId,Store,Brand,Description,Size,VendorNumber,VendorName,PONumber,PODate,ReceivingDate,InvoiceDate,PayDate,PurchasePrice,Quantity,Dollars,Classification
0,69_MOUNTMEND_8412,69,8412,Tequila Ocho Plata Fresno,750mL,105,ALTAMAR BRANDS LLC,8124,2023-12-21,2024-01-02,2024-01-04,2024-02-16,35.71,6,214.26,1
1,30_CULCHETH_5255,30,5255,TGI Fridays Ultimte Mudslide,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8137,2023-12-22,2024-01-01,2024-01-07,2024-02-21,9.35,4,37.40,1
2,34_PITMERDEN_5215,34,5215,TGI Fridays Long Island Iced,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8137,2023-12-22,2024-01-02,2024-01-07,2024-02-21,9.41,5,47.05,1
3,1_HARDERSFIELD_5255,1,5255,TGI Fridays Ultimte Mudslide,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8137,2023-12-22,2024-01-01,2024-01-07,2024-02-21,9.35,6,56.10,1
4,76_DONCASTER_2034,76,2034,Glendalough Double Barrel,750mL,388,ATLANTIC IMPORTING COMPANY,8169,2023-12-24,2024-01-02,2024-01-09,2024-02-16,21.32,5,106.60,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2372469,49_GARIGILL_22298,49,22298,Zorvino Vyds Sangiovese,750mL,90058,ZORVINO VINEYARDS,13593,2024-12-19,2024-12-28,2025-01-09,2025-02-06,8.06,12,96.72,2
2372470,1_HARDERSFIELD_19556,1,19556,Zorvino Bacca Z Blackberry,750mL,90058,ZORVINO VINEYARDS,13593,2024-12-19,2024-12-27,2025-01-09,2025-02-06,9.39,12,112.68,2
2372471,66_EANVERNESS_22297,66,22297,Zorvino Vyds Pearz,750mL,90058,ZORVINO VINEYARDS,13593,2024-12-19,2024-12-26,2025-01-09,2025-02-06,6.75,12,81.00,2
2372472,69_MOUNTMEND_19557,69,19557,Zorvino Fragole Z Strawberry,750mL,90058,ZORVINO VINEYARDS,13593,2024-12-19,2024-12-26,2025-01-09,2025-02-06,9.39,12,112.68,2
2372473,55_DRY GULCH_22298,55,22298,Zorvino Vyds Sangiovese,750mL,90058,ZORVINO VINEYARDS,13593,2024-12-19,2024-12-28,2025-01-09,2025-02-06,8.06,12,96.72,2

-------------------------------------------------- purchase_prices --------------------------------------------------
Count of Records: 12261

,Brand,Description,Price,Size,Volume,Classification,PurchasePrice,VendorNumber,VendorName
0,58,Gekkeikan Black & Gold Sake,12.99,750mL,750,1,9.28,8320,SHAW ROSS INT L IMP LTD
1,62,Herradura Silver Tequila,36.99,750mL,750,1,28.67,1128,BROWN-FORMAN CORP
2,63,Herradura Reposado Tequila,38.99,750mL,750,1,30.46,1128,BROWN-FORMAN CORP
3,72,No. 3 London Dry Gin,34.99,750mL,750,1,26.11,9165,ULTRA BEVERAGE COMPANY LLP
4,75,Three Olives Tomato Vodka,14.99,750mL,750,1,10.94,7245,PROXIMO SPIRITS INC.
...,...,...,...,...,...,...,...,...,...
12256,44917,Ferreira 10-Yr Tawny Port,24.99,750mL,750,2,16.55,90024,VINILANDIA USA
12257,44944,Sanford Santa Rita Pnt Nr,22.99,750mL,750,2,14.93,4425,MARTIGNETTI COMPANIES
12258,45016,Neal One Lane Bridg Cab Svgn,93.99,750mL,750,2,61.43,10754,PERFECTA WINES
12259,46011,Folonari Pnt Nr Venezie,12.99,1500ml,1500,2,8.90,9744,FREDERICK WILDMAN & SONS
12260,46964,Calera Viognier Mt Harlan,35.99,750mL,750,2,24.32,10754,PERFECTA WINES

-------------------------------------------------- sales --------------------------------------------------
Count of Records: 12825363

,InventoryId,Store,Brand,Description,Size,SalesQuantity,SalesDollars,SalesPrice,SalesDate,Volume,Classification,ExciseTax,VendorNo,VendorName
0,1_HARDERSFIELD_1004,1,1004,Jim Beam w/2 Rocks Glasses,750mL,1,16.49,16.49,2024-01-01,750.0,1,0.79,12546,JIM BEAM BRANDS COMPANY
1,1_HARDERSFIELD_1004,1,1004,Jim Beam w/2 Rocks Glasses,750mL,2,32.98,16.49,2024-01-02,750.0,1,1.57,12546,JIM BEAM BRANDS COMPANY
2,1_HARDERSFIELD_1004,1,1004,Jim Beam w/2 Rocks Glasses,750mL,1,16.49,16.49,2024-01-03,750.0,1,0.79,12546,JIM BEAM BRANDS COMPANY
3,1_HARDERSFIELD_1004,1,1004,Jim Beam w/2 Rocks Glasses,750mL,1,14.49,14.49,2024-01-08,750.0,1,0.79,12546,JIM BEAM BRANDS COMPANY
4,1_HARDERSFIELD_1005,1,1005,Maker's Mark Combo Pack,375mL 2 Pk,2,69.98,34.99,2024-01-09,375.0,1,0.79,12546,JIM BEAM BRANDS COMPANY
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12825358,9_BLACKPOOL_984,9,984,Patron XO Cafe Liqueur,750mL,1,25.99,25.99,2024-12-17,750.0,1,0.79,9165,ULTRA BEVERAGE COMPANY LLP
12825359,9_BLACKPOOL_984,9,984,Patron XO Cafe Liqueur,750mL,1,25.99,25.99,2024-12-21,750.0,1,0.79,9165,ULTRA BEVERAGE COMPANY LLP
12825360,9_BLACKPOOL_984,9,984,Patron XO Cafe Liqueur,750mL,3,77.97,25.99,2024-12-23,750.0,1,2.36,9165,ULTRA BEVERAGE COMPANY LLP
12825361,9_BLACKPOOL_984,9,984,Patron XO Cafe Liqueur,750mL,1,25.99,25.99,2024-12-24,750.0,1,0.79,9165,ULTRA BEVERAGE COMPANY LLP
12825362,9_BLACKPOOL_984,9,984,Patron XO Cafe Liqueur,750mL,2,51.98,25.99,2024-12-29,750.0,1,1.57,9165,ULTRA BEVERAGE COMPANY LLP

-------------------------------------------------- vendor_invoice --------------------------------------------------
Count of Records: 5543

,VendorNumber,VendorName,InvoiceDate,PONumber,PODate,PayDate,Quantity,Dollars,Freight,Approval
0,105,ALTAMAR BRANDS LLC,2024-01-04,8124,2023-12-21,2024-02-16,6,214.26,3.47,None
1,4466,AMERICAN VINTAGE BEVERAGE,2024-01-07,8137,2023-12-22,2024-02-21,15,140.55,8.57,None
2,388,ATLANTIC IMPORTING COMPANY,2024-01-09,8169,2023-12-24,2024-02-16,5,106.60,4.61,None
3,480,BACARDI USA INC,2024-01-12,8106,2023-12-20,2024-02-05,10100,137483.78,2935.20,None
4,516,BANFI PRODUCTS CORP,2024-01-07,8170,2023-12-24,2024-02-12,1935,15527.25,429.20,None
...,...,...,...,...,...,...,...,...,...,...
5538,9622,WEIN BAUER INC,2025-01-06,13626,2024-12-21,2025-02-10,90,1563.00,8.60,None
5539,9625,WESTERN SPIRITS BEVERAGE CO,2025-01-10,13661,2024-12-23,2025-02-18,4617,37300.48,186.50,None
5540,3664,WILLIAM GRANT & SONS INC,2025-01-02,13643,2024-12-22,2025-02-04,9848,202815.78,932.95,None
5541,9815,WINE GROUP INC,2025-01-03,13602,2024-12-20,2025-02-08,24747,149007.56,819.54,None
5542,90058,ZORVINO VINEYARDS,2025-01-05,13574,2024-12-18,2025-02-12,437,3608.11,16.60,None

-------------------------------------------------- vendor_sales_summary --------------------------------------------------
Count of Records: 0

Empty DataFrame
Columns: [VendorNumber, VendorName, Brand, Description, PurchasePrice, ActualPrice, Volume, TotalPurchaseDollars, TotalSalesQuantity, TotalSalesDollars, TotalSalesPrice, TotalExciseTax, FreightCost, GrossProfit, ProfitMargin, StockTurnOver, SalesToPurchaseRatio]
Index: []

-------------------------------------------------- vendor_sales_sumary --------------------------------------------------
Count of Records: 0

Empty DataFrame
Columns: [VendorNumber, VendorName, Brand, Description, PurchasePrice, ActualPrice, Volume, TotalPurchaseQuantity, TotalPurchaseDollars, TotalSalesQuantity, TotalSalesDollars, TotalSalesPrice, TotalExciseTax, FreightCost, GrossProfit, ProfitMargin, StockTurnOver, SalesToPurchaseRatio]
Index: []

-------------------------------------------------- vendor_sales_number --------------------------------------------------
Count of Records: 10692

,VendorNumber,VendorName,Brand,Description,PurchasePrice,ActualPrice,Volume,TotalPurchaseQuantity,TotalPurchaseDollars,TotalSalesQuantity,TotalSalesDollars,TotalSalesPrice,TotalExciseTax,FreightCost,GrossProfit,ProfitMargin,StockTurnOver,SalesToPurchaseRatio
0,1128,BROWN-FORMAN CORP,1233,Jack Daniels No 7 Black,26.27,36.99,1750.0,145080,3811251.60,142049.0,5101919.51,672819.31,260999.20,68601.68,1290667.91,33.864673,0.979108,1.338647
1,4425,MARTIGNETTI COMPANIES,3405,Tito's Handmade Vodka,23.19,28.99,1750.0,164038,3804041.22,160247.0,4819073.49,561512.37,294438.66,144929.24,1015032.27,26.682999,0.976890,1.266830
2,17035,PERNOD RICARD USA,8068,Absolut 80 Proof,18.24,24.99,1750.0,187407,3418303.68,187140.0,4538120.60,461140.15,343854.07,123780.22,1119816.92,32.759433,0.998575,1.327594
3,3960,DIAGEO NORTH AMERICA INC,4261,Capt Morgan Spiced Rum,16.17,22.99,1750.0,201682,3261197.94,200412.0,4475972.88,420050.01,368242.80,257032.07,1214774.94,37.249347,0.993703,1.372493
4,3960,DIAGEO NORTH AMERICA INC,3545,Ketel One Vodka,21.89,29.99,1750.0,138109,3023206.01,135838.0,4223107.62,545778.28,249587.83,257032.07,1199901.61,39.689707,0.983556,1.396897
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10687,9815,WINE GROUP INC,8527,Concannon Glen Ellen Wh Zin,1.32,4.99,750.0,2,2.64,5.0,15.95,10.96,0.55,27100.41,13.31,504.166667,2.500000,6.041667
10688,8004,SAZERAC CO INC,5683,Dr McGillicuddy's Apple Pie,0.39,0.49,50.0,6,2.34,134.0,65.66,1.47,7.04,50293.62,63.32,2705.982906,22.333333,28.059829
10689,3924,HEAVEN HILL DISTILLERIES,9123,Deep Eddy Vodka,0.74,0.99,50.0,2,1.48,2.0,1.98,0.99,0.10,14069.87,0.50,33.783784,1.000000,1.337838
10690,3960,DIAGEO NORTH AMERICA INC,6127,The Club Strawbry Margarita,1.47,1.99,200.0,1,1.47,72.0,143.28,77.61,15.12,257032.07,141.81,9646.938776,72.000000,97.469388
10691,7245,PROXIMO SPIRITS INC.,3065,Three Olives Grape Vodka,0.71,0.99,50.0,1,0.71,86.0,85.14,33.66,4.46,38994.78,84.43,11891.549296,86.000000,119.915493

In [13]:
purchases=pd.read_sql_query("select * from purchases where VendorNumber=4466",conn)
purchases

,InventoryId,Store,Brand,Description,Size,VendorNumber,VendorName,PONumber,PODate,ReceivingDate,InvoiceDate,PayDate,PurchasePrice,Quantity,Dollars,Classification
0,30_CULCHETH_5255,30,5255,TGI Fridays Ultimte Mudslide,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8137,2023-12-22,2024-01-01,2024-01-07,2024-02-21,9.35,4,37.40,1
1,34_PITMERDEN_5215,34,5215,TGI Fridays Long Island Iced,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8137,2023-12-22,2024-01-02,2024-01-07,2024-02-21,9.41,5,47.05,1
2,1_HARDERSFIELD_5255,1,5255,TGI Fridays Ultimte Mudslide,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8137,2023-12-22,2024-01-01,2024-01-07,2024-02-21,9.35,6,56.10,1
3,38_GOULCREST_5215,38,5215,TGI Fridays Long Island Iced,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8207,2023-12-27,2024-01-07,2024-01-19,2024-02-26,9.41,6,56.46,1
4,59_CLAETHORPES_5215,59,5215,TGI Fridays Long Island Iced,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8207,2023-12-27,2024-01-05,2024-01-19,2024-02-26,9.41,6,56.46,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2187,81_PEMBROKE_5215,81,5215,TGI Fridays Long Island Iced,1.75L,4466,AMERICAN VINTAGE BEVERAGE,13595,2024-12-20,2024-12-29,2025-01-04,2025-02-10,9.41,6,56.46,1
2188,62_KILMARNOCK_5255,62,5255,TGI Fridays Ultimte Mudslide,1.75L,4466,AMERICAN VINTAGE BEVERAGE,13595,2024-12-20,2024-12-28,2025-01-04,2025-02-10,9.35,5,46.75,1
2189,34_PITMERDEN_5215,34,5215,TGI Fridays Long Island Iced,1.75L,4466,AMERICAN VINTAGE BEVERAGE,13595,2024-12-20,2024-12-28,2025-01-04,2025-02-10,9.41,5,47.05,1
2190,6_GOULCREST_5215,6,5215,TGI Fridays Long Island Iced,1.75L,4466,AMERICAN VINTAGE BEVERAGE,13595,2024-12-20,2024-12-31,2025-01-04,2025-02-10,9.41,6,56.46,1
2191,35_HALIVAARA_5255,35,5255,TGI Fridays Ultimte Mudslide,1.75L,4466,AMERICAN VINTAGE BEVERAGE,13595,2024-12-20,2024-12-27,2025-01-04,2025-02-10,9.35,5,46.75,1

In [14]:
purchases.groupby(['Brand','PurchasePrice'])[['Quantity','Dollars']].sum()

                     Quantity   Dollars
Brand PurchasePrice
3140  11.19              4640  51921.60
5215  9.41               4923  46325.43
5255  9.35               6215  58110.25

In [5]:
sales = pd.read_sql("SELECT * FROM sales", conn)
sales.groupby('Brand')[['SalesDollars','SalesPrice','SalesQuantity']].sum()

       SalesDollars  SalesPrice  SalesQuantity
Brand
58         43341.54    28145.64           3446
60         18716.25    10720.79           1775
61          4364.88      363.74            312
62        119863.75    90154.51           3125
63        112249.22    88553.10           2778
...             ...         ...            ...
90089      19078.41     5759.52            159
90090       9749.85     4549.93             15
90604       9119.24     2639.78             76
90609       2074.17     1774.29             83
90631      31504.41    19502.73           1659

[11237 rows x 3 columns]

In [18]:
freight_summary=pd.read_sql_query("""select VendorNumber,SUM(Freight) as FreightCost From vendor_invoice Group By VendorNumber""",conn)

In [19]:
freight_summary

     VendorNumber  FreightCost
0               2        27.08
1              54         0.48
2              60       367.52
3             105        62.39
4             200         6.19
..            ...          ...
121         98450       856.02
122         99166       130.09
123        172662       178.34
124        173357       202.50
125        201359         0.09

[126 rows x 2 columns]

In [22]:
pd.read_sql_query("""select p.VendorNumber,p.VendorName,p.Brand,p.PurchasePrice,SUM(p.Quantity) as totalquantity,SUM(p.Dollars) as totalpurchasedollars,pp.Volume,pp.Price as ActualPrice from purchases p join  purchase_prices pp on p.brand=pp.brand where p.PurchasePrice>0 group by p.VendorNumber,p.VendorName,p.Brand order by totalpurchasedollars """,conn)

,VendorNumber,VendorName,Brand,PurchasePrice,totalquantity,totalpurchasedollars,Volume,ActualPrice
0,7245,PROXIMO SPIRITS INC.,3065,0.71,1,0.71,50,0.99
1,3960,DIAGEO NORTH AMERICA INC,6127,1.47,1,1.47,200,1.99
2,3924,HEAVEN HILL DISTILLERIES,9123,0.74,2,1.48,50,0.99
3,8004,SAZERAC CO INC,5683,0.39,6,2.34,50,0.49
4,9815,WINE GROUP INC,8527,1.32,2,2.64,750,4.99
...,...,...,...,...,...,...,...,...
10687,3960,DIAGEO NORTH AMERICA INC,3545,21.89,138109,3023206.01,1750,29.99
10688,3960,DIAGEO NORTH AMERICA INC,4261,16.17,201682,3261197.94,1750,22.99
10689,17035,PERNOD RICARD USA,8068,18.24,187407,3418303.68,1750,24.99
10690,4425,MARTIGNETTI COMPANIES,3405,23.19,164038,3804041.22,1750,28.99
10691,1128,BROWN-FORMAN CORP,1233,26.27,145080,3811251.60,1750,36.99

In [6]:
import time
import pandas as pd
import sqlite3

In [7]:
vendor_sales_summary=pd.read_sql_query("""WITH FreightSummary AS(
         SELECT VendorNumber,SUM(Freight) as FreightCost from vendor_invoice group by VendorNumber),
         PurchaseSummary AS(
         SELECT p.VendorNumber,p.VendorName,p.Brand,p.Description,p.PurchasePrice,pp.Price as ActualPrice,pp.Volume,SUM(p.Quantity) as TotalPurchaseQuantity,SUM(p.Dollars) as TotalPurchaseDollars from purchases p join purchase_prices pp on p.Brand=pp.Brand where p.PurchasePrice>0 group by p.VendorNumber,p.VendorName,p.Brand,p.Description,p.PurchasePrice,pp.Price,pp.Volume),
         SalesSummary as(
         SELECT VendorNo,Brand,SUM(SalesQuantity) as TotalSalesQuantity,SUM(SalesDollars) as TotalSalesDollars,SUM(SalesPrice) as TotalSalesPrice,SUM(ExciseTax) as TotalExciseTax FROM Sales GROUP BY VendorNo,Brand)
         SELECT ps.VendorNumber,ps.VendorName,ps.Brand,ps.Description,ps.PurchasePrice,ps.ActualPrice,ps.Volume,ps.TotalPurchaseQuantity,ps.TotalPurchaseDollars,ss.TotalSalesQuantity,ss.TotalSalesDollars,ss.TotalSalesPrice,ss.TotalExciseTax,fs.FreightCost from PurchaseSummary ps left join SalesSummary ss on ps.VendorNumber=ss.VendorNo and ps.Brand=ss.Brand left join FreightSummary fs on ps.VendorNumber=fs.VendorNumber order by ps.TotalPurchaseDollars DESC""",conn)

In [10]:
vendor_sales_summary.to_csv(
r"C:\Users\4sin\Downloads\data\data\vendor_sales_summary.csv",
index=False
)

In [13]:
vendor_sales_summary.dtypes

VendorNumber               int64
VendorName                object
Brand                      int64
Description               object
PurchasePrice            float64
ActualPrice              float64
Volume                    object
TotalPurchaseQuantity      int64
TotalPurchaseDollars     float64
TotalSalesQuantity       float64
TotalSalesDollars        float64
TotalSalesPrice          float64
TotalExciseTax           float64
FreightCost              float64
dtype: object

In [14]:
vendor_sales_summary.isnull().sum()

VendorNumber               0
VendorName                 0
Brand                      0
Description                0
PurchasePrice              0
ActualPrice                0
Volume                     0
TotalPurchaseQuantity      0
TotalPurchaseDollars       0
TotalSalesQuantity       178
TotalSalesDollars        178
TotalSalesPrice          178
TotalExciseTax           178
FreightCost                0
dtype: int64

In [15]:
vendor_sales_summary['VendorName'].unique()

array(['BROWN-FORMAN CORP          ', 'MARTIGNETTI COMPANIES',
       'PERNOD RICARD USA          ', 'DIAGEO NORTH AMERICA INC   ',
       'BACARDI USA INC            ', 'JIM BEAM BRANDS COMPANY    ',
       'MAJESTIC FINE WINES        ', 'ULTRA BEVERAGE COMPANY LLP ',
       'STOLI GROUP,(USA) LLC      ', 'PROXIMO SPIRITS INC.       ',
       'MOET HENNESSY USA INC      ', 'CAMPARI AMERICA            ',
       'SAZERAC CO INC             ', 'CONSTELLATION BRANDS INC   ',
       'M S WALKER INC             ', 'SAZERAC NORTH AMERICA INC. ',
       'PALM BAY INTERNATIONAL INC ', 'REMY COINTREAU USA INC     ',
       'SIDNEY FRANK IMPORTING CO  ', 'E & J GALLO WINERY         ',
       'WILLIAM GRANT & SONS INC   ', 'HEAVEN HILL DISTILLERIES   ',
       'DISARONNO INTERNATIONAL LLC', 'EDRINGTON AMERICAS         ',
       'CASTLE BRANDS CORP.        ', 'SOUTHERN WINE & SPIRITS NE ',
       'STE MICHELLE WINE ESTATES  ', 'TRINCHERO FAMILY ESTATES   ',
       'MHW LTD                    ', 'WINE GROUP INC             ',
       'PERFECTA WINES             ', 'LUXCO INC                  ',
       'TREASURY WINE ESTATES      ', 'DIAGEO CHATEAU ESTATE WINES',
       'SHAW ROSS INT L IMP LTD    ', 'PINE STATE TRADING CO      ',
       'PHILLIPS PRODUCTS CO.      ', 'CALEDONIA SPIRITS INC      ',
       'STATE WINE & SPIRITS   ', 'KOBRAND CORPORATION        ',
       'BANFI PRODUCTS CORP        ', 'VINEYARD BRANDS INC        ',
       'DELICATO VINEYARDS INC     ', 'FABRIZIA SPIRITS LLC       ',
       'DUGGANS DISTILLED PRODUCTS ', 'Serralles Usa LLC          ',
       'SEA HAGG DISTILLERY LLC    ', 'OLE SMOKY DISTILLERY LLC   ',
       'VRANKEN AMERICA            ', 'KLIN SPIRITS LLC           ',
       'LAIRD & CO                 ', 'ADAMBA IMPORTS INTL INC    ',
       'LATITUDE BEVERAGE COMPANY  ', 'FREDERICK WILDMAN & SONS   ',
       'MCCORMICK DISTILLING CO    ', 'CHARLES JACQUIN ET CIE INC ',
       'WESTERN SPIRITS BEVERAGE CO', 'MARSALLE COMPANY           ',
       'AMERICAN VINTAGE BEVERAGE  ', 'MANGO BOTTLING INC         ',
       'SWEET BABY VINEYARD        ', 'NICHE W & S                ',
       'LABELLE VYDS AND WINERY    ', 'FLAG HILL WINERY & VINEYARD',
       'SMOKY QUARTZ DISTILLERY LLC', 'PREMIUM PORT WINES, INC.   ',
       'Russian Standard Vodka     ', 'Dunn Wine Brokers          ',
       'WEIN BAUER INC             ', 'BULLY BOY DISTILLERS       ',
       'ATLANTIC IMPORTING COMPANY ', 'PREMIER DISTRIBUTORS       ',
       'VINILANDIA USA             ', 'PARK STREET IMPORTS LLC    ',
       'TAKARA SAKE USA INC        ', 'SEA BREEZE CELLARS LLC     ',
       'STARK BREWING COMPANY      ', 'TY KU LLC                  ',
       'PSP WINES ', 'TAMWORTH DISTILLING        ',
       'ZORVINO VINEYARDS          ', 'SOUTHERN GLAZERS W&S OF NE ',
       'HOOD RIVER DISTILLERS, Inc.', 'CRUSH WINES                ',
       'POVERTY LANE ORCHARDS      ', 'DJINN SPIRITS LLC          ',
       'MOONLIGHT MEADERY          ', 'TALL SHIP DISTILLERY LLC   ',
       'FORTUNE WINE BROKERS LLC   ', 'BLACK COVE BEVERAGES       ',
       'VINEXTRA INC               ', 'SURVILLE ENTERPRISES CORP  ',
       'JEWELL TOWNE VINEYARDS     ', 'SWEETWATER FARM         ',
       'MARTIGNETTI COMPANIES ', 'ALTAMAR BRANDS LLC         ',
       'CANDIA VINEYARDS           ', 'INCREDIBREW INC            ',
       'ALISA CARR BEVERAGES           ', 'STELLAR IMPORTING CO LLC   ',
       'FULCHINO VINEYARD INC      ',
       'IRA GOLDMAN AND WILLIAMS, LLP          ',
       'Circa Wines                ', 'VINEDREA WINES LLC         ',
       'BLACK PRINCE DISTILLERY INC', 'VINEYARD BRANDS LLC        ',
       'THE IMPORTED GRAPE LLC     ', 'WALPOLE MTN VIEW WINERY    ',
       'GILMANTON WINERY & VINEYARD', 'HAUNTING WHISPER VYDS      ',
       'STAR INDUSTRIES INC.       ', 'LOYAL DOG WINERY           ',
       'R.P.IMPORTS INC            ', 'THE PIERPONT GROUP LLC     ',
       'APPOLO VINEYARDS LLC       ', 'BLACK ROCK SPIRITS LLC     ',
       'CENTEUR IMPORTS LLC        ', 'HIGHLAND WINE MERCHANTS LLC',
       'AMERICAN SPIRITS EXCHANGE  ', 'UNCORKED       ',
       'BRONCO WINE COMPANY        ', 'MILTONS DISTRIBUTING CO    ',
       'TRUETT HURST               ', 'LAUREATE IMPORTS CO        ',
       'FANTASY FINE WINES CORP    ', 'AAPER ALCOHOL & CHEMICAL CO',
       'SILVER MOUNTAIN CIDERS     ', 'CAPSTONE INTERNATIONAL     ',
       'FLAVOR ESSENCE INC         '], dtype=object)

In [16]:
vendor_sales_summary['Description'].unique()

array(['Jack Daniels No 7 Black', "Tito's Handmade Vodka",
       'Absolut 80 Proof', ..., 'Crown Royal Apple',
       'Concannon Glen Ellen Wh Zin', 'The Club Strawbry Margarita'],
      dtype=object)

In [17]:
vendor_sales_summary['Volume']=vendor_sales_summary['Volume'].astype("float64")

In [18]:
vendor_sales_summary.fillna(0,inplace=True)

In [19]:
vendor_sales_summary['VendorName']=vendor_sales_summary['VendorName'].str.strip()

In [20]:
vendor_sales_summary['GrossProfit']=vendor_sales_summary['TotalSalesDollars']-vendor_sales_summary['TotalPurchaseDollars']

In [11]:
vendor_sales_summary.to_csv(
r"C:\Users\4sin\Downloads\data\data\vendor_sales_summary.csv",
index=False
)

In [21]:
vendor_sales_summary['GrossProfit'].min()

-52002.780000000006

In [22]:
vendor_sales_summary['ProfitMargin']=(vendor_sales_summary['GrossProfit']/vendor_sales_summary['TotalPurchaseDollars'])*100

In [21]:
vendor_sales_summary

,VendorNumber,VendorName,Brand,Description,PurchasePrice,ActualPrice,Volume,TotalPurchaseQuantity,TotalPurchaseDollars,TotalSalesQuantity,TotalSalesDollars,TotalSalesPrice,TotalExciseTax,FreightCost,GrossProfit,ProfitMargin
0,1128,BROWN-FORMAN CORP,1233,Jack Daniels No 7 Black,26.27,36.99,1750.0,145080,3811251.60,142049.0,5101919.51,672819.31,260999.20,68601.68,1290667.91,33.864673
1,4425,MARTIGNETTI COMPANIES,3405,Tito's Handmade Vodka,23.19,28.99,1750.0,164038,3804041.22,160247.0,4819073.49,561512.37,294438.66,144929.24,1015032.27,26.682999
2,17035,PERNOD RICARD USA,8068,Absolut 80 Proof,18.24,24.99,1750.0,187407,3418303.68,187140.0,4538120.60,461140.15,343854.07,123780.22,1119816.92,32.759433
3,3960,DIAGEO NORTH AMERICA INC,4261,Capt Morgan Spiced Rum,16.17,22.99,1750.0,201682,3261197.94,200412.0,4475972.88,420050.01,368242.80,257032.07,1214774.94,37.249347
4,3960,DIAGEO NORTH AMERICA INC,3545,Ketel One Vodka,21.89,29.99,1750.0,138109,3023206.01,135838.0,4223107.62,545778.28,249587.83,257032.07,1199901.61,39.689707
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10687,9815,WINE GROUP INC,8527,Concannon Glen Ellen Wh Zin,1.32,4.99,750.0,2,2.64,5.0,15.95,10.96,0.55,27100.41,13.31,504.166667
10688,8004,SAZERAC CO INC,5683,Dr McGillicuddy's Apple Pie,0.39,0.49,50.0,6,2.34,134.0,65.66,1.47,7.04,50293.62,63.32,2705.982906
10689,3924,HEAVEN HILL DISTILLERIES,9123,Deep Eddy Vodka,0.74,0.99,50.0,2,1.48,2.0,1.98,0.99,0.10,14069.87,0.50,33.783784
10690,3960,DIAGEO NORTH AMERICA INC,6127,The Club Strawbry Margarita,1.47,1.99,200.0,1,1.47,72.0,143.28,77.61,15.12,257032.07,141.81,9646.938776
10691,7245,PROXIMO SPIRITS INC.,3065,Three Olives Grape Vodka,0.71,0.99,50.0,1,0.71,86.0,85.14,33.66,4.46,38994.78,84.43,11891.549296

In [23]:
vendor_sales_summary['SalesToPurchaseRatio']=vendor_sales_summary['TotalSalesDollars']/vendor_sales_summary['TotalPurchaseDollars']

In [24]:
cursor=conn.cursor()

In [10]:
cursor.execute("DROP TABLE IF EXISTS vendor_sales_summary")

In [11]:
cursor.execute("""CREATE TABLE vendor_sales_summary(
VendorNumber INT,	
VendorName VARCHAR(100),	
Brand INT,
Description VARCHAR(100),	
PurchasePrice DECIMAL(15,2),	
ActualPrice DECIMAL(15,2),
Volume INT,
TotalPurchaseQuantity INT,
TotalPurchaseDollars DECIMAL(15,2),	
TotalSalesQuantity INT,
TotalSalesDollars DECIMAL(15,2),
TotalSalesPrice DECIMAL(15,2),
TotalExciseTax DECIMAL(15,2),
FreightCost DECIMAL(15,2),
GrossProfit DECIMAL(15,2),
ProfitMargin DECIMAL(15,2), 
StockTurnOver DECIMAL(15,2), 
SalesToPurchaseRatio DECIMAL(15,2))""")

In [25]:
vendor_sales_summary.to_sql('vendor_sales_summary',conn,if_exists='replace',index=False)
vendor_sales_summary.to_csv(
r"C:\Users\4sin\Downloads\data\data\vendor_sales_summary.csv",
index=False
)

In [13]:
cursor.execute("SELECT name FROM sqlite_master WHERE type='table';")
print(cursor.fetchall())

[('begin_inventory',), ('end_inventory',), ('purchases',), ('purchase_prices',), ('sales',), ('vendor_invoice',), ('vendor_sales_sumary',), ('vendor_sales_number',), ('vendor_sales_summary',)]

In [14]:
conn.close()

In [15]:
def create_vendor_summary(conn):
    '''this function will merge the different tables to get overall vendor summary and adding new columns in the resultant data'''
    vendor_sales_summary=pd.read_sql("""WITH FreightSummary AS(
         SELECT VendorNumber,SUM(Freight) as FreightCost from vendor_invoice group by VendorNumber),
         
         PurchaseSummary AS(
         SELECT p.VendorNumber,p.VendorName,p.Brand,p.Description,p.PurchasePrice,pp.Price as ActualPrice,pp.Volume,SUM(p.Quantity) as TotalPurchaseQuantity,SUM(p.Dollars) as TotalPurchaseDollars from purchases p join purchase_prices pp on p.Brand=pp.Brand where p.PurchasePrice>0 group by p.VendorNumber,p.VendorName,p.Brand,p.Description,p.PurchasePrice,pp.Price,pp.Volume),
        
         SalesSummary as(
         SELECT VendorNo,Brand,SUM(SalesQuantity) as TotalSalesQuantity,SUM(SalesDollars) as TotalSalesDollars,SUM(SalesPrice) as TotalSalesPrice,SUM(ExciseTax) as TotalExciseTax FROM Sales GROUP BY VendorNo,Brand)
         SELECT ps.VendorNumber,ps.VendorName,ps.Brand,ps.Description,ps.PurchasePrice,ps.ActualPrice,ps.Volume,ps.TotalPurchaseQuantity,ps.TotalPurchaseDollars,ss.TotalSalesQuantity,ss.TotalSalesDollars,ss.TotalSalesPrice,ss.TotalExciseTax,fs.FreightCost from PurchaseSummary ps left join SalesSummary ss on ps.VendorNumber=ss.VendorNo and ps.Brand=ss.Brand left join FreightSummary fs on ps.VendorNumber=fs.VendorNumber order by ps.TotalPurchaseDollars DESC""",conn)
    return vendor_sales_summary
def clean_data(df):
    '''this function will clean the data'''
    #change datatype to float
    df['Volume']=df['Volume'].astype('float')
    df.fillna(0,inplace=True)
    #removing spaces from categorical columns
    df['VendorName']=df['VendorName'].str.strip()
    df['Description']=df['Description'].str.strip()
    #creating new columns for better analysis
    vendor_sales_summary['GrossProfit']=vendor_sales_summary['TotalSalesDollars']-vendor_sales_summary['TotalPurchaseDollars']
    vendor_sales_summary['ProfitMargin']=(vendor_sales_summary['GrossProfit']/vendor_sales_summary['TotalPurchaseDollars'])*100
    vendor_sales_summary['StockTurnover']=vendor_sales_summary['TotalSalesQuantity']/vendor_sales_summary['TotalPurchaseQuantity']
    vendor_sales_summary['SalesToPurchaseRatio']=vendor_sales_summary['TotalSalesDollars']/vendor_sales_summary['TotalPurchaseDollars']
    return df
if __name__=='__main__':
    #creating database connection
    conn=sqlite3.connect('inventory.db')
    logging.info('Creating Vendor Summary Table')
    summary_df=create_vendor_summary(conn)
    logging.info(summary_df.head())
    logging.info('Cleaning Data')
    clean_df=clean_data(summary_df)
    logging.info(clean_df.head())
    logging.info("ingesting data...")
    ingest_db(clean_df,"vendor_sales_summary",conn)
    logging.info("completed")

In [22]:
cursor.execute("PRAGMA table_info(vendor_sales_summary)")
print(cursor.fetchall())

[(0, 'VendorNumber', 'INTEGER', 0, None, 0), (1, 'VendorName', 'TEXT', 0, None, 0), (2, 'Brand', 'INTEGER', 0, None, 0), (3, 'Description', 'TEXT', 0, None, 0), (4, 'PurchasePrice', 'REAL', 0, None, 0), (5, 'ActualPrice', 'REAL', 0, None, 0), (6, 'Volume', 'REAL', 0, None, 0), (7, 'TotalPurchaseQuantity', 'INTEGER', 0, None, 0), (8, 'TotalPurchaseDollars', 'REAL', 0, None, 0), (9, 'TotalSalesQuantity', 'REAL', 0, None, 0), (10, 'TotalSalesDollars', 'REAL', 0, None, 0), (11, 'TotalSalesPrice', 'REAL', 0, None, 0), (12, 'TotalExciseTax', 'REAL', 0, None, 0), (13, 'FreightCost', 'REAL', 0, None, 0), (14, 'GrossProfit', 'REAL', 0, None, 0), (15, 'ProfitMargin', 'REAL', 0, None, 0), (16, 'SalesToPurchaseRatio', 'REAL', 0, None, 0)]

In [21]:
cursor.execute("ALTER TABLE vendor_sales_summary ADD COLUMN GrossProfit REAL")
cursor.execute("ALTER TABLE vendor_sales_summary ADD COLUMN ProfitMargin REAL")
cursor.execute("ALTER TABLE vendor_sales_summary ADD COLUMN SalesToPurchaseRatio REAL")

conn.commit()

In [23]:
cursor.execute("ALTER TABLE vendor_sales_summary ADD COLUMN StockTurnover REAL")
conn.commit()

In [5]:
cursor.execute("""
UPDATE vendor_sales_summary
SET GrossProfit = TotalSalesDollars - TotalPurchaseDollars
""")

cursor.execute("""
UPDATE vendor_sales_summary
SET ProfitMargin = (GrossProfit / TotalSalesDollars) * 100
""")

cursor.execute("""
UPDATE vendor_sales_summary
SET SalesToPurchaseRatio = TotalSalesDollars / TotalPurchaseDollars
""")

cursor.execute("""
UPDATE vendor_sales_summary
SET StockTurnover = TotalSalesQuantity / TotalPurchaseQuantity
""")

conn.commit()

In [6]:
import pandas as pd

pd.read_sql("""
SELECT VendorName, GrossProfit, ProfitMargin, SalesToPurchaseRatio, StockTurnover
FROM vendor_sales_summary
LIMIT 10
""", conn)

,VendorName,GrossProfit,ProfitMargin,SalesToPurchaseRatio,StockTurnover
0,BROWN-FORMAN CORP,1290667.91,25.297693,1.338647,0.979108
1,MARTIGNETTI COMPANIES,1015032.27,21.062810,1.266830,0.976890
2,PERNOD RICARD USA,1119816.92,24.675786,1.327594,0.998575
3,DIAGEO NORTH AMERICA INC,1214774.94,27.139908,1.372493,0.993703
4,DIAGEO NORTH AMERICA INC,1199901.61,28.412764,1.396897,0.983556
5,BACARDI USA INC,917276.47,27.106980,1.371873,1.021980
6,PERNOD RICARD USA,596082.65,21.493098,1.273773,0.983668
7,DIAGEO NORTH AMERICA INC,503706.51,19.432812,1.241200,0.918698
8,DIAGEO NORTH AMERICA INC,736751.64,27.902068,1.387002,0.985256
9,JIM BEAM BRANDS COMPANY,661966.25,27.181081,1.373269,0.983420